version: "3.9"

services:
  mysql-shop-db:
    image: mysql:8.0.30
    restart: always
    volumes:
      - ./docker/:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASS}

  redis-shop-cache:
    image: redis
    container_name: redis-shop-cache
    restart: always
    ports:
      - "6379:6379"
